### PR TITLE
Disable asm-processor for progress calculation

### PR DESCRIPTION
**Pull request by Yanis42**
ported from oot-gc

### CODE REVIEW

**Comment by cadmic** [comment]
CI is still failing, but I don't think it's too important rn since we can't use asm-processor anyway

**Comment by Yanis42** [comment]
yeah I noticed that but I'm not sure how to fix it, it fails because of this: ``build/oot-j/oot-vc.dol: FAILED`` btw

**Comment by cadmic** [comment]
`--non-matching` is supposed to disable the checksum check so maybe that needs to be ported over too?

**Comment by Yanis42** [comment]
I'm confused, when I build with ``--non-matching`` myself it doesn't do the checksum check

**Comment by Yanis42** [comment]
iirc we agreed to remove it yesterday so I'm closing this PR

**Pull request closed without merging**
